settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wely-fun # unique identifier
    name: Wely | 主页
    description: '这里是 Wely 的主页' # default=empty
    url: 'https://Wely.fun/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-wely-fun
    name: Wely | 博客
    description: '这里是 Wely 的博客'
    url: 'https://blog.wely.fun/'
    method: GET
    expectStatus: 200

  - id: work-wely-in
    name: Wely 镜像 GitHub
    description: '通过 Cloudflare Workers 反向代理 GitHub'
    url: 'https://work.wely.in/'
    method: GET
    expectStatus: 200

  - id: s-wely-in
    name: Wely 短链接
    description: '缩短一个长网址'
    url: 'https://s.wely.in/'
    method: GET
    expectStatus: 200
